app/modules/admin_c27/controllers/CategoryController.php
<?php

    class CategoryController extends AdminController {

        public function accessRules() {
            return array(
                array(
                    'allow',
                    'actions' => array(
                        'login',
                        'logout',
                        'error'
                    ),
                    'users'   => array( '*' ),
                ),
                array(
                    'allow',
                    'roles' => array( 'admin' ),
                ),
                array(
                    'deny',
                    'users' => array( '*' ),
                ),
            );
        }

        public function actionIndex() {
            $category = Category::model()->getAllCategory();

            $this->render(
                'index', array(
                    'category' => $category
                )
            );
        }

        public function actionUpdateIndex() {
            $data = json_decode($_POST[ 'data' ], true);

            $position = 0;
            foreach ($data as $_next) {
                $position++;
                $id = intval($_next[ 'key' ]);
                Category::model()->updateByPk(
                    $id, array(
                        'position'        => $position,
                        'parent_position' => null,
                        'parent'          => null
                    )
                );
                if (isset( $_next[ 'children' ] )) {
                    $positionChild = 1;
                    foreach ($_next[ 'children' ] as $_child) {
                        $position++;
                        $idChild = intval($_child[ 'key' ]);
                        Category::model()->updateByPk(
                            intval($_child[ 'key' ]), array(
                                'position'        => $position,
                                'parent'          => $id,
                                'parent_position' => $positionChild
                            )
                        );

                        $positionChild++;

                        if (isset( $_child[ 'children' ] )) {
                            $positionChildTwo = 1;
                            foreach ($_child[ 'children' ] as $_childTwo) {
                                $position++;
                                Category::model()->updateByPk(
                                    intval($_childTwo[ 'key' ]), array(
                                        'position'        => $position,
                                        'parent'          => $idChild,
                                        'parent_position' => $positionChildTwo
                                    )
                                );
                                $positionChildTwo++;
                            }
                        }
                    }
                }
            }

        }

        public function actionUpdate() {
            $id = $_POST[ 'id' ];
            $newName = $_POST[ 'newName' ];

            Category::model()->updateByPk(intval($id), array( 'name' => $newName ));
        }

        public function actionLogin() {
            $model = new LoginForm;

            // if it is ajax validation request
            if (isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'login-form') {
                echo CActiveForm::validate($model);
                Yii::app()->end();
            }

            // collect user input data
            if (isset( $_POST[ 'LoginForm' ] )) {
                $model->attributes = $_POST[ 'LoginForm' ];
                // validate user input and redirect to the previous page if valid
                if ($model->validate() && $model->login())
                    $this->redirect(Yii::app()->user->returnUrl);
            }
            // display the login form
            $this->renderPartial('login', array( 'model' => $model ));
        }

        /**
         * This is the action to handle external exceptions.
         */
        public function actionError() {
            if ($error = Yii::app()->errorHandler->error) {
                if (Yii::app()->request->isAjaxRequest)
                    echo $error[ 'message' ]; else
                    $this->render('error', $error);
            }
        }

        public function actionDelete($id) {
            Category::model()->deleteByPk($id);
            $allChild = Category::model()->findAllByAttributes(array( 'parent' => $id ));
            foreach ($allChild as $_child) {
                $_child->parent = null;
                Category::model()->updateByPk(
                    $_child->id, array(
                        'parent' => null,
                    )
                );
            }
        }

        public function actionAdd() {
            $name = $_POST[ 'name' ];
            $category = new Category();

            $category->name = $name;
            if (isset( $_POST[ 'id' ] ))
                $category->parent = $_POST[ 'id' ];

            $category->position = $category->getMaxPosition() + 1;
            $category->date_create = AddExtend::getDateNow();
            if (!$category->save()) {
                exit( CJSON::encode(array_merge($category->getErrors(), array( 'error' => 'Некорректно заполнены поля' ))) );
            } else {
                exit( CJSON::encode($category->attributes) );
            }
        }

        /**
         * Return buttons for elem
         *
         * @param $id
         *
         * @return string
         */
        public function buttonBlock($id) {
            return '
        <div class="btnCat">
            <span class="view' . $id . '">
                <a title="Просмотеть товары категории" href="' . AddExtend::getURL($this, "/goods/index/id/" . $id . "/type/cat") . '">
                    <img class = "view" src="' . AddExtend::baseUrl() . 'shared/media/css/admin/images/admin/visible.png" class="viewEYE"/>
                </a>
            </span>
            <span class="edit' . $id . '">
                <img title="Переименовать" src="' . AddExtend::baseUrl() . 'shared/media/css/admin/images/admin/edit.png"/>
            </span>
            <span class="delete' . $id . '">
                <img title="Удалить" src="' . AddExtend::baseUrl() . 'shared/media/css/admin/images/admin/delete.png"/>
            </span>
        </div>';
        }
    }

app/modules/admin_c27/controllers/DefaultController.php
<?php

    class DefaultController extends AdminController {
        private $md5prefix = "SE34dwe4xk034sdk5mep23bsEN";

        public function accessRules() {
            return array(
                array(
                    'allow',
                    'actions' => array(
                        'login',
                        'logout',
                        'error'
                    ),
                    'users'   => array( '*' ),
                ),
                array(
                    'allow',
                    'roles' => array( 'admin' ),
                ),
                array(
                    'deny',
                    'users' => array( '*' ),
                ),
            );
        }

        public function actionIndex() {

            $criteria = new CDbCriteria();
            $criteria->select = 'count(id) as id, country, city';
            $criteria->group = 'country';
            $criteria->order = "id DESC";
            $visitors = Visitors::model()->findAll($criteria);

            $totalCount = Yii::app()->db->createCommand("SELECT count(id) as id FROM " . Visitors::model()->tableName())->queryScalar();

            $order = array(
                'all' => OrderMain::getCountOrder(),
                'buy' => OrderMain::getCountOrder('status_pay = \'pay\''),
            );

            $countUser = Yii::app()->db->createCommand("SELECT count(id) as id FROM " . Users::model()->tableName())->queryScalar();


            $systemInfo = AddExtend::getSystemInfo();

            $this->render('index', array(
                    'visitors'   => $visitors,
                    'orders'     => $order,
                    'countUsers' => $countUser,
                    'systemInfo' => $systemInfo,
                    'total'      => $totalCount
                )
            );
        }

        public function actionLogin() {
            $model = new LoginForm;

            // if it is ajax validation request
            if (isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'login-form') {
                echo CActiveForm::validate($model);
                Yii::app()->end();
            }

            // collect user input data
            if (isset( $_POST[ 'LoginForm' ] )) {
                $model->attributes = $_POST[ 'LoginForm' ];
                // validate user input and redirect to the previous page if valid
                if ($model->validate() && $model->login()) {
                    $url = Yii::app()->user->returnUrl;
                    if ($url == '/' || $url == '/index.php')
                        $this->redirect(Yii::app()->createUrl($this->module->id . '/default/index'));
                    $this->redirect($url);
                }
            }
            // display the login form
            $this->renderPartial('login', array( 'model' => $model ));
        }

        public function actionLogout() {
            Yii::app()->user->logout(true);
            $this->redirect(AddExtend::getURL($this, "/default/login"));
        }

        /**
         * This is the action to handle external exceptions.
         */
        public function actionError() {
            if ($error = Yii::app()->errorHandler->error) {
                if (Yii::app()->request->isAjaxRequest)
                    echo $error[ 'message' ]; else
                    $this->render('error', $error);
            }
        }

    }

app/modules/admin_c27/controllers/OrdersController.php
<?php

    class OrdersController extends AdminController {

        public function accessRules() {
            return array(
                array(
                    'allow',
                    'actions' => array(
                        'login',
                        'logout',
                        'error'
                    ),
                    'users'   => array( '*' ),
                ),
                array(
                    'allow',
                    'roles' => array( 'admin' ),
                ),
                array(
                    'deny',
                    'users' => array( '*' ),
                ),
            );
        }

        public function actionIndex() {
            $order = new OrderMain('search');
            $order->unsetAttributes();
            if (isset($_POST[ 'OrderMain' ]))
                $order->attributes = $_POST['OrderMain'];

            $this->render('index', array(
                    'order' => $order
                )
            );
        }

        public function actionView ($id) {
            $order = new Order('search');
            $order->unsetAttributes();

            if (isset($_POST[ 'Order' ])) {
                $order->attributes = $_POST[ 'Order' ];
            }

            $order->order_id = $id;

            $this->render('detail/index', array(
                    'order' => $order
                )
            );
        }

        public function actionDelete ($id) {
            Order::model()->deleteByPk($id);
        }

        public function actionDeleteOrderMain ($id) {
            OrderMain::model()->deleteByPk($id);
        }

        public function actionUpdate ($id) {
            if (isset($_POST[ 'status' ])) {
                /** @var OrderMain $order */
                $order = OrderMain::model()->findByPk($id);
                if ($order) {
                    $order->status = $_POST['status'];
                    if (isset($_POST['statusPay']))
                        $order->status_pay = $_POST['statusPay'];

                    if (isset($_POST['statusPay']))
                        $order->status_delivery = $_POST['statusDelivery'];

                    $order->update();
                    $allChildOrder = Order::model()->findAllByAttributes(array('order_id' => $order->getPrimaryKey()));
                    /** @var Order $_child */
                    foreach ($allChildOrder as $_child) {
                        $_child->status = $_POST[ 'status' ];
                    }
                }
            }
        }

        public function actionLogin() {
            $model = new LoginForm;

            // if it is ajax validation request
            if (isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'login-form') {
                echo CActiveForm::validate($model);
                Yii::app()->end();
            }

            // collect user input data
            if (isset( $_POST[ 'LoginForm' ] )) {
                $model->attributes = $_POST[ 'LoginForm' ];
                // validate user input and redirect to the previous page if valid
                if ($model->validate() && $model->login())
                    $this->redirect(Yii::app()->user->returnUrl);
            }
            // display the login form
            $this->renderPartial('login', array( 'model' => $model ));
        }

        /**
         * This is the action to handle external exceptions.
         */
        public function actionError() {
            if ($error = Yii::app()->errorHandler->error) {
                if (Yii::app()->request->isAjaxRequest)
                    echo $error[ 'message' ]; else
                    $this->render('error', $error);
            }
        }

    }

app/modules/admin_c27/views/layouts/main.php
<!doctype html>
<html lang = "ru">

<head>
    <script>
        var adminUrl = '<?=AddExtend::getURL($this, '')?>';
        var baseUrl = '<?=AddExtend::baseUrl()?>';
        // Заглушка в IE для console
        if (typeof console === 'undefined')
            console = {
                log : function (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {

                }
            };
        var controller = "<?=$this->id?>";
    </script>

    <?php AddExtend::regCoreScript('jquery'); ?>
    <meta charset = "UTF-8" />

    <link rel = "stylesheet" href = "<?= AddExtend::baseUrl(true) ?>shared/media/bootstrap3/css/bootstrap.min.css" />

    <link rel = "stylesheet" href = "<?= AddExtend::baseUrl(true) ?>shared/media/bootstrap3/css/AdminLTE.css" />

    <link href = "<?= AddExtend::baseUrl(true) ?>shared/media/bootstrap3/css/font-awesome.min.css" rel = "stylesheet"
          type = "text/css" />
    <!-- Ionicons -->
    <link href = "<?= AddExtend::baseUrl(true) ?>shared/media/bootstrap3/css/ionicons.min.css" rel = "stylesheet"
          type = "text/css" />
    <!-- Morris chart -->
    <link href = "<?= AddExtend::baseUrl(true) ?>shared/media/bootstrap3/css/morris/morris.css" rel = "stylesheet"
          type = "text/css" />
    <!-- jvectormap -->
    <link href = "<?= AddExtend::baseUrl(true) ?>shared/media/bootstrap3/css/jvectormap/jquery-jvectormap-1.2.2.css"
          rel = "stylesheet" type = "text/css" />
    <!-- fullCalendar -->
    <link href = "<?= AddExtend::baseUrl(true) ?>shared/media/bootstrap3/css/fullcalendar/fullcalendar.css"
          rel = "stylesheet" type = "text/css" />
    <!-- Daterange picker -->
    <link href = "<?= AddExtend::baseUrl(true) ?>shared/media/bootstrap3/css/daterangepicker/daterangepicker-bs3.css"
          rel = "stylesheet" type = "text/css" />
    <!-- bootstrap wysihtml5 - text editor -->
    <link
        href = "<?= AddExtend::baseUrl(true) ?>shared/media/bootstrap3/css/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css"
        rel = "stylesheet" type = "text/css" />

    <link href = "<?= AddExtend::baseUrl(true) ?>shared/media/css/admin/admin.css" rel = "stylesheet"
          type = "text/css" />

    <!--    <script type="text/javascript" src="-->
    <? //=AddExtend::baseUrl(true)?><!--/bootstrap3/js/bootstrap.min.js"></script>-->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src = "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src = "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <title><?= Yii::app()->name ?> - <?= $this->pageTitle ?></title>
    <script src = "<?= AddExtend::baseUrl(true) ?>/shared/media/js/admin/formStyle.js"></script>
    <link href = "<?= AddExtend::baseUrl(true) ?>shared/media/css/admin/dialog.css" rel = "stylesheet"
          type = "text/css" />

</head>

<body class = "skin-black fixed wysihtml5-supported pace-done">
<!-- header logo: style can be found in header.less -->
<header class = "header">
    <a href = "<?= AddExtend::getURL($this); ?>" class = "logo" style = "line-height: 0; padding: 0">
        <!-- Add the class icon to your logo image or logo icon to add the margining -->
        <img src = "<?= AddExtend::baseUrl(true); ?>shared/media/images/logo_new_admin.png">
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class = "navbar navbar-static-top" role = "navigation">
        <!-- Sidebar toggle button-->
        <a href = "#" class = "navbar-btn sidebar-toggle" data-toggle = "offcanvas" role = "button">
            <span class = "sr-only">Toggle navigation</span>
            <span class = "icon-bar"></span>
            <span class = "icon-bar"></span>
            <span class = "icon-bar"></span>
        </a>
        <div class = "navbar-right">
            <ul class = "nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class = "dropdown user user-menu">
                    <div class = "pull-right" style = "margin-top: 7px;">
                        <a href = "<?= Yii::app()->createUrl('site/index') ?>"
                           class = "btn btn-default btn-flat" target = "_blank">На сайт
                        </a>
                    </div>
                </li>
                <li class = "dropdown user user-menu">
                    <div class = "pull-right" style = "margin-top: 7px;">
                        <a href = "<?= Yii::app()->createUrl(AddExtend::getURL($this, '/default/logout', false)) ?>"
                           class = "btn btn-default btn-flat">Выход (<?= Yii::app()->user->username ?>)
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</header>
<div class = "wrapper row-offcanvas row-offcanvas-left">
    <!-- Left side column. contains the logo and sidebar -->
    <aside class = "left-side sidebar-offcanvas">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class = "sidebar">
            <ul class = "sidebar-menu">
                <li>
                    <a href = "<?= AddExtend::getURL($this, '/users/index') ?>">
                        <i class = "fa fa-users<?= AddExtend::activeLink('/users') ?>"></i>
                        <span>Пользователи</span>
                    </a>
                </li>
                <li>
                    <a href = "<?= AddExtend::getURL($this, '/mainpage/index') ?>">
                        <i class = "fa fa-desktop<?= AddExtend::activeLink('/mainpage') ?>"></i>
                        <span>Главная страница</span>
                    </a>
                </li>
                <li>
                    <a href = "<?= AddExtend::getURL($this, '/category/index') ?>">
                        <i class = "fa fa-list<?= AddExtend::activeLink('/category') ?>"></i>
                        <span>Категории</span>
                    </a>
                </li>
                <li>
                    <a href = "<?= AddExtend::getURL($this, '/producer/index') ?>">
                        <i class = "fa fa-archive<?= AddExtend::activeLink('/producer') ?>"></i>
                        <span>Производители</span>
                    </a>
                </li>
                <li>
                    <a href = "<?= AddExtend::getURL($this, '/goods/index') ?>">
                        <i class = "fa fa-briefcase<?= AddExtend::activeLink('/goods') ?>"></i>
                        <span>Товары</span>
                    </a>
                </li>
                <li>
                    <a href = "<?= AddExtend::getURL($this, '/orders/index') ?>">
                        <i class = "fa fa-euro<?= AddExtend::activeLink('/orders') ?>"></i>
                        <span>Заказы</span>
                    </a>
                </li>
                <li class = "treeview<?= AddExtend::activeLink(array('/delivery', '/pay', '/change', '/contacts', '/phrase')) ?>">
                    <a href = "<?= AddExtend::getURL($this, '/contacts/index') ?>">
                        <i class = "fa fa-toggle-down<?= AddExtend::activeLink('/contacts') ?>"></i>
                        <span>О компании</span>
                        <i class = "fa fa-angle-left pull-right"></i>
                    </a>
                    <ul class = "treeview-menu">
                        <li>
                            <a href = "<?= AddExtend::getURL($this, '/pay/index') ?>">
                                <i class = "fa fa-money<?= AddExtend::activeLink('/pay') ?>"></i>
                                <span>Способы оплаты</span>
                            </a>
                        </li>
                        <li>
                            <a href = "<?= AddExtend::getURL($this, '/delivery/index') ?>">
                                <i class = "fa fa-dashboard<?= AddExtend::activeLink('/delivery') ?>"></i>
                                <span>Доставка товара</span>
                            </a>
                        </li>
                        <li>
                            <a href = "<?= AddExtend::getURL($this, '/change/index') ?>">
                                <i class = "fa fa-bug<?= AddExtend::activeLink('/change') ?>"></i>
                                <span>Возврат товара</span>
                            </a>
                        </li>
                        <li>
                            <a href = "<?= AddExtend::getURL($this, '/contacts/index') ?>">
                                <i class = "fa fa-book<?= AddExtend::activeLink('/contacts') ?>"></i>
                                <span>Контактная информация</span>
                            </a>
                        </li>
                        <li>
                            <a href = "<?= AddExtend::getURL($this, '/phrase/index') ?>">
                                <i class = "fa fa-hand-o-right<?= AddExtend::activeLink('/phrase') ?>"></i>
                                <span>Фразы байкеров</span>
                            </a>
                        </li>
                    </ul>
                </li>

            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Right side column. Contains the navbar and content of the page -->
    <aside class = "right-side">
        <!-- Main content -->
        <section class = "content">
            <?= $content ?>
        </section>
        <!-- /.content -->
    </aside>
    <!-- /.right-side -->
</div>
<!-- ./wrapper -->

<script src = "<?= AddExtend::baseUrl(true) ?>shared/media/bootstrap3/js/jquery-ui-1.10.3.min.js"
        type = "text/javascript"></script>
<!-- Bootstrap -->
<script src = "<?= AddExtend::baseUrl(true) ?>shared/media/bootstrap3/js/bootstrap.min.js"
        type = "text/javascript"></script>
<!-- AdminLTE App -->
<script src = "<?= AddExtend::baseUrl(true) ?>shared/media/bootstrap3/js/AdminLTE/app.js"
        type = "text/javascript"></script>

</body>
</html>