app/modules/admin_c27/controllers/UsersController.php
<?php

    class UsersController extends AdminController {

        public $pageTitle = "Users";

        public function accessRules() {
            return array(
                array(
                    'allow',
                    'actions' => array(
                        'login',
                        'logout',
                        'error'
                    ),
                    'users'   => array( '*' ),
                ),
                array(
                    'allow',
                    'roles' => array( 'admin' ),
                ),
                array(
                    'deny',
                    'users' => array( '*' ),
                ),
            );
        }

        public function actionIndex() {
            $users = new Users('search');
            $users->unsetAttributes();

            if (isset( $_POST[ 'Users' ] )) {
                $users->attributes = $_POST[ 'Users' ];
            }

            $this->render(
                'index', array(
                    'users' => $users
                )
            );
        }

        public function actionLogin() {
            $model = new LoginForm;

            // if it is ajax validation request
            if (isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'login-form') {
                echo CActiveForm::validate($model);
                Yii::app()->end();
            }

            // collect user input data
            if (isset( $_POST[ 'LoginForm' ] )) {
                $model->attributes = $_POST[ 'LoginForm' ];
                // validate user input and redirect to the previous page if valid
                if ($model->validate() && $model->login())
                    $this->redirect(Yii::app()->user->returnUrl);
            }
            // display the login form
            $this->renderPartial('login', array( 'model' => $model ));
        }

        /**
         * This is the action to handle external exceptions.
         */
        public function actionError() {
            if ($error = Yii::app()->errorHandler->error) {
                if (Yii::app()->request->isAjaxRequest)
                    echo $error[ 'message' ]; else
                    $this->render('error', $error);
            }
        }

        public function actionAdd() {
            $this->actionUpdate(0);
        }

        public function actionUpdate($id) {
            //        $id = intval($id);
            if ($id == 0) {
                $user = new Users();
                $address[ 0 ] = new Address();
            } else {
                $user = Users::model()->findByPk($id);
                $address = Address::model()->findAllByAttributes(array(), "user_id=:uId", array( ':uId' => $id ));
            }

            if (AddExtend::isAjax() && !isset( $_POST[ 'saveData' ] )) {
                if (isset( $_POST[ 'Users' ] )) {
                    $user->attributes = $_POST[ 'User' ];
                    echo CActiveForm::validate($user);
                }
                Yii::app()->end();
            }
            $ok = false;

            if (isset( $_POST[ 'Users' ] )) {
                foreach ($_POST[ 'Users' ] as $key => $val)
                    $user[ $key ] = $val;

                $user->birthday = date('Y-m-d', $user->birthday);

                if (is_null($user->register_date))
                    $user->register_date = date('d-m-y H:m:s');

                if ($user->validate())
                    if ($id > 0) {
                        if ($user->update()) {
                            $ok = true;
                        }
                    } else {
                        if ($user->save())
                            $ok = true;
                    }
            }

            if (isset( $_POST[ 'Address' ] )) {
                $save = true;
                foreach ($_POST[ 'Address' ] as $key => $value) {
                    if (!isset( $address[ $key ] ))
                        $address[ $key ] = new Address();

                    $address[ $key ]->attributes = $value;
                    if ($id <= 0) {
                        $address[ $key ][ 'user_id' ] = $user->getPrimaryKey();
                    }

                    if (is_null($address[ $key ][ 'date_add' ]))
                        $address[ $key ][ 'date_add' ] = date('d-m-y H:m:s');

                    if (!$address[ $key ]->validate())
                        $save = false; else if ($id > 0)
                        if (isset( $address[ 'key' ]->id ) && !is_null($address[ 'key' ]->id) && $id > 0) {
                            if (!$address[ $key ]->update())
                                $save = false;
                        } else {
                            if (!$address[ $key ]->save())
                                $save = false;
                        } else {
                        if (!$address[ $key ]->save()) {
                            $save = false;
                        }
                    }
                }
                if ($save && $ok)
                    $ok = true;
                else
                    $ok = false;
            }

            if ($ok)
                if (!isset( $_POST[ 'saveData' ] ))
                    $this->redirect(AddExtend::getURL($this, "/users/index"));
                else
                    exit( json_encode(
                        array(
                            'url' => AddExtend::getURL($this, "users/index")
                        )
                    ) );
            else {
            }
            $this->render(
                'update', array(
                    'user'     => $user,
                    'adresses' => $address
                )
            );
        }

        public function actionDeleteAddress($id) {
            if (!is_numeric($id)) {
                exit;
            } else {
                $userAddress = Address::model()->findByPk($id);
                $userAddress->delete();
            }
        }

        public function actionDelete($id) {
            $user = Users::model()->findByPk($id);
            $user->delete();
        }
    }

app/modules/admin_c27/views/users/index.php
<a href = "<?= AddExtend::getURL($this, '/users/add') ?>" style = "color: white; text-decoration: none;"
   class = "btn btn-primary">
    Добавить нового
</a>
<?php
    $this->widget(
        'zii.widgets.grid.CGridView', array(
            'id'               => 'users-list',
            'dataProvider'     => $users->search(),
            'ajaxType'         => 'POST',
            'filter'           => $users,
            'enablePagination' => true,
            'itemsCssClass'    => 'table table-bordered table-striped dataTable',
            'template'         => '{items}{pager}',
//            'filterCssClass'   => 'form-control',
            'pager'            => array(
                'header'               => '',
                'prevPageLabel'        => '<',
                'nextPageLabel'        => '>',
                'lastPageLabel'        => '>>',
                'firstPageLabel'       => '<<',
                'hiddenPageCssClass'   => '',
                'pageSize'             => 50,
                'htmlOptions'          => array( 'class' => 'pagination pagination-centered' ),
                'selectedPageCssClass' => 'active',
            ),
            'pagerCssClass'    => 'p',
            'columns'          => array(
                'id',
                'email',
                'username',
                'last_name',
                'first_name',
                'middle_name',
                'birthday',
                'city',
                'phone',
                array(
                    'name'   => 'role',
                    'value'  => function ($data) {
                        return ( ( ( $data->role == 'admin' ) ? 'Администратор' : 'Пользователь' ) );
                    },
                    'filter' => array(
                        '' => 'Все',
                        'admin' => 'Администратор',
                        'user'  => 'Пользователь',
                    ),
                ),
                array(
                    'name'   => 'subscribe',
                    'value'  => function ($data) {
                        return ( ( $data->subscribe ) ? 'Подписан' : 'Не подписан' );
                    },
                    'filter' => array(
                        '' => 'Все',
                        '0' => 'Не подписан',
                        '1' => 'Подписан'
                    )
                ),

                array(
                    'class'       => 'CButtonColumn',
                    'htmlOptions' => array(
                        'style' => 'width: 80px'
                    ),
                    'template'    => '<div style="width: 43px!important;">{update}{delete}</div>',
                    'buttons'     => array(
                        'update' => array(
                            'title' => 'Редактировать',
                            'imageUrl' => AddExtend::pathCss() . "admin/images/admin/edit.png"
                        ),
                        'delete' => array(
                            'title' => 'Удалить',
                            'imageUrl' => AddExtend::pathCss() . "admin/images/admin/delete.png"
                        ),
                    ),
                )
            )
        )
    );

app/modules/admin_c27/views/users/update.php
<?php
    AddExtend::regScriptFile(AddExtend::baseUrl() . "shared/media/js/admin/users.js");
    AddExtend::regCssFile(array(
                              AddExtend::pathCss() . 'admin/fix.css'
                          ), 'screen'
    );
?>
<script type = "text/javascript">
    var userID = <?= intval($user->id) ?>;
</script>
<div>

    <div>
        <?php
            echo '<div id="user_update_form_widget">';
            $form = $this->beginWidget(
                'CActiveForm', array(
                    'id'                   => 'user_update',
                    'action'               => AddExtend::getURL($this, $this->id . '/update/id/' . $_GET[ 'id' ]),
                    'enableAjaxValidation' => true,
                )
            );


            ?>
        <div class='row'>
            <div class="nextField">
                <?= $form->labelEx($user, 'last_name') ?>
                <?= $form->textField($user, 'last_name') ?>
                <?= $form->error($user, 'last_name'); ?>
            </div>
            <div class="nextField">
                <?= $form->labelEx($user, 'first_name') ?>
                <?= $form->textField($user, 'first_name') ?>
                <?= $form->error($user, 'first_name'); ?>
            </div>
            <div class="nextField">
                <?= $form->labelEx($user, 'username') ?>
                <?= $form->textField($user, 'username') ?>
                <?= $form->error($user, 'username'); ?>

            </div>
        </div>
        <div class="row">
            <div class="nextField">
                <?= $form->labelEx($user, 'role') ?>
                <?= $form->dropDownList($user, 'role', array(
                        'user'  => 'Пользователь',
                        'admin' => 'Администратор'
                    )
                ) ?>
                <?= $form->error($user, 'role'); ?>
            </div>
            <div class="nextField">
                <?= $form->labelEx($user, 'subscribe') ?>
                <?= $form->dropDownList($user, 'subscribe', array(
                        '0' => 'Не подписан',
                        '1' => 'Подписан'
                    )
                ) ?>
                <?= $form->error($user, 'last_name'); ?>
            </div>
            <div class="nextField">
                <?= $form->labelEx($user, 'birthday') ?>
                <?php
                    $dateRange = '1920:' . date("Y",time());
                    $date = new DateTime();
                    $date->modify('- 18 year');
                    $date->modify('- 1 day');
                    $this->widget(
                        'zii.widgets.jui.CJuiDatePicker', array(
                            'name'     => 'Users[birthday]',
                            'model'    => $user,
                            'value'    => date('d-m-Y', $user->birthday),
                            'language' => 'ru',
                            'options'  => array(
                                'showAnim'        => 'slide',
                                'dateFormat'      => 'dd-mm-yy',
                                'changeMonth'     => true,
                                'changeYear'      => true,
                                'yearRange'       => $dateRange,
                                'minDate'         => '01-01-1920',
                                'maxDate'         => $date->format('d-m-Y'),
                                'showButtonPanel' => true
                            ),
                        )
                    );
                ?>
                <?= $form->error($user, 'birthday'); ?>
            </div>
        </div>
        <div class="row">
            <div class="nextField">
                <?= $form->labelEx($user, 'email') ?>
                <?= $form->textField($user, 'email') ?>
                <?= $form->error($user, 'email'); ?>
            </div>
            <div class="nextField">
                <?= $form->labelEx($user, 'phone') ?>
                <?= $form->textField($user, 'phone') ?>
                <?= $form->error($user, 'phone'); ?>
            </div>
        </div>
    <?php
        echo "<div style='clear: both'>  </div>";
        echo '<div style="float: left;"><button id="addAddress" class="btn btn-primary" style="clear: both;">Добавить адрес</button></div>';
        echo "<div style='clear: both'></div>";


        echo "<table class='table table-bordered table-striped dataTable' style=\"width:777px\">";
        echo "<tr><td>№</td><td>Страна</td><td>Город</td><td>Улица</td><td>Дом</td><td>Квартира</td><td></td></tr>";
        foreach ($adresses as $keyAddress => $value) {
            if (isset( $value->attributes )) {
                $trShow = false;
                foreach ($value->attributes as $key => $attr) {
                    if ($key == 'id' || $key == 'user_id' || $key == 'date_add') {

                        echo $form->hiddenField($value, $key, array( 'name' => 'Address[' . $keyAddress . '][' . $key . ']' )) . "";

                    } else {

                        if (!$trShow)
                            echo "<tr><td class='numRowAddress'>" . intval($keyAddress + 1) . "</td>";
                        $trShow = true;

                        echo "<td>" . $form->textField($value, $key, array( 'name' => 'Address[' . $keyAddress . '][' . $key . ']' )) . "";

                        echo $form->error($value, $key, array( 'name' => 'Address[' . $keyAddress . '][' . $key . ']' )) . "</td>";

                    }
                }
                if ($trShow) {
                    echo "<td><div class='deleteIcon' number=\"{$value['id']}\"><img width=16 height=16 src='" . AddExtend::baseUrl() . "shared/media/css/admin/images/admin/delete.png'/></div></td>";
                    echo "</tr>";
                }
            }
        }
        echo "</table>";
    ?>
</div>
<?php echo "<div class='clear submitButton_user'>" . CHtml::submitButton('Сохранить', array( 'class' => 'btn btn-success' )) . "</button></div>";
    $this->endWidget();

?>
</div>